// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectDetails.Helper;

#nullable disable

namespace ProjectDetails.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250422051144_UpdateStatusType")]
    partial class UpdateStatusType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("ProjectDetails.Models.paymentDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("JonyAmount")
                        .IsRequired();

                    b.Property<string>("JonyStatus")
                        .IsRequired();

                    b.Property<string>("PaidAmountPercentage")
                        .IsRequired();

                    b.Property<string>("ProjectName")
                        .IsRequired();

                    b.Property<string>("ShahadotAmount")
                        .IsRequired();

                    b.Property<string>("ShahadotStatus")
                        .IsRequired();

                    b.Property<int>("Status");

                    b.Property<string>("TotalCost")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("paymentDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
